### ISSUE TITLE
Release apk is crashing on android devices

### ISSUE THREAD

**Issue by Aadiyaara** [solutelabs/Flutchat#10]
I have tried extracting the debug apk and installing it separately as well as release apk on my phone and some other phones too. For some reason the Built app crashes on opening, but runs fine in emulator and on the same phones but when in the flutter dev environment

**Comment by milind-mevada-stl** [comment]
@Aadiyaara Can you provide more information on this? For me, it's working fine on fresh release install.

Note here, you have to provide your API keys for the Tokbox project. (Check the readme for detailed information)

**Comment by milind-mevada-stl** [comment]
Closing due to not active for a long time.
