### ISSUE TITLE
Location of sdk

### ISSUE THREAD

**Issue by MilindDivre** [solutelabs/Flutchat#9]
Can you pls brief about where the sdk should be placed in flutter folder structure. ? actually i am planning to use different sdk  and integrate it with flutter. But not getting how we can package sdk. can you pls help

**Comment by pabloamg** [comment]
do you mean The Tokbox SDK? the Tokbox SDK  is available as a pod

for ios you add it to your PodFile

`target 'Runner' do
  ...
  pod 'OpenTok'`

for android:

project build.gradlle :
`allprojects {
    repositories {
        ...
        maven { url "http://tokbox.bintray.com/maven" }
    }
}`

module build.graddle:

`dependencies {
  ...
  implementation 'com.opentok.android:opentok-android-sdk:2.15.3'
}`

**Comment by milind-mevada-stl** [comment]
I hope this is clear by @pabloamg comment.
